### ISSUE TITLE
All dynamically created kinds are tagged as partition #0 in jemalloc.

### ISSUE THREAD

**Issue by krzycz** [memkind/memkind#1]
All the dynamically created kinds that use *jemalloc* arenas (see `memkind_arena(3)`) are tagged as partition #0. So, in practice, for those kinds `memkind_malloc` is equivalent to `je_malloc`, and all the memory is actually allocated from the default system heap.

**Comment by cmcantalupo** [comment]
Thanks Krzysztof.  Merged your patch to dev.
