### ISSUE TITLE
Should memkind_create_pmem check for DAX option in mounted directory?

### ISSUE THREAD

**Issue by haraldservat** [memkind/memkind#107]
When running the following code with memkind (master - revision 21bf2e0 - dated 09th Oct 2018) and passing it the paramater /tmp (which is a  regular /tmp partition , i.e. not supporting DAX), I get a "Successful message".

I believe that  memkind_create_pmem should fail if parameter 1 (path) is not a DAX filesystem, right?

```
# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <memkind.h>

int main(int argc, char *argv[])
{
        if (argc != 2)
        {
                fprintf (stderr, "Error! Missing directory to pass to memkind_create_pmem\n");
                return -2;
        }
        printf ("Invoking: memkind_get_version();\nReturned: %d\n", memkind_get_version());
        memkind_t pmem_kind;
        printf ("Invoking: memkind_create_pmem (\"%s\", 0, %p);\n", argv[1], &pmem_kind);
        int err = memkind_create_pmem (argv[1], 0, &pmem_kind);
        if (err)
        {
                char msg[1024];
                memkind_error_message (err, msg, sizeof(msg));
                fprintf (stderr,"Returned: Error during memkind_create_pmem: %s\n", msg);
                return -1;
        }
        printf ("Returned: Successful!\n");
        return 0;
}
```

Here are the output of the commands:

```
$ make
gcc -O -g test1.c -o test1 -I/nfs/pdx/home/hservatg/aplic/memkind/20181009/include -L/nfs/pdx/home/hservatg/aplic/memkind/20181009/lib -Wl,-rpath -Wl,/nfs/pdx/home/hservatg/aplic/memkind/20181009/lib -lmemkind
$ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
.$ /test1 /tmp
Invoking: memkind_get_version();
Returned: 1007000
Invoking: memkind_create_pmem ("/tmp", 0, 0x7ffd80f5b4d8);
Returned: Successful!
```

**Comment by michalbiesek** [comment]
Hi,
Thank You for your question. 

Actually we don't want to block the usage of memkind_create_pmem function regarding supporting DAX or not.
According to the documentation (**memkind_pmem.3**):
 _The pmem memkinds are **most useful** when used with Direct Access storage (DAX), which is memory-addressable persistent storage that supports load/store access without being paged via the system
       page cache._

For me ( trying to use it without DAX ) looks like configuration issue - not related to memkind itself.

**Comment by haraldservat** [comment]
Thanks for your answer Michal. I understand your point.

However, what remains unclear then is: where does memkind get memory from when using a filesystem that does not support DAX? If in this case it gets memory from the regular memory pool, isn't it misleading? Shouldn't it return a null pointer because the device cannot provide memory?

Thanks!

**Comment by michalbiesek** [comment]
Hi,
If a filesystem will not support DAX, it will use page cache.
But still for me it looks like configuration issue. IMHO  it isn't memkind responsibility to check for dax devices - this configuration check.
_Shouldn't it return a null pointer because the device cannot provide memory?_
I'm not sure if I follow You. **memkind_create_pmem** return int status. In case of trying allocation(memkind_malloc,memkind_calloc...)  **memkind_pmem_mmap** function is called. See that there is a **posix_fallocate** and **mmap**, not in memkind_create_pmem.
Allocation function will return NULL, if there will be no sufficient memory in location/path passed in memkind_create_pmem, in other words if "device cannot provide memory"

**Comment by haraldservat** [comment]
Ok thanks for the exaplanation. I think now I understand.
