### ISSUE TITLE
Unclear messages from memkind_create_pmem error?

### ISSUE THREAD

**Issue by haraldservat** [memkind/memkind#108]
The following simplistic code using memkind master (revision 21bf2e0 dated 09th Oct 2018) reports always the same error string from memkind_error_message routine. I always get 
  <memkind> Unspecified run-time error
 no matter the given directory exists or does not have rwx permissions.

Am I doing something wrong on processing the message or should the library provide clearer error messages?

```
# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <memkind.h>

int main(int argc, char *argv[])
{
        if (argc != 2)
        {
                fprintf (stderr, "Error! Missing directory to pass to memkind_create_pmem\n");
                return -2;
        }
        printf ("Invoking: memkind_get_version();\nReturned: %d\n", memkind_get_version());
        memkind_t pmem_kind;
        printf ("Invoking: memkind_create_pmem (\"%s\", 0, %p);\n", argv[1], &pmem_kind);
        int err = memkind_create_pmem (argv[1], 0, &pmem_kind);
        if (err)
        {
                char msg[1024];
                memkind_error_message (err, msg, sizeof(msg));
                fprintf (stderr,"Returned: Error during memkind_create_pmem: %s\n", msg);
                return -1;
        }
        printf ("Returned: Successful!\n");
        return 0;
}
```

**Comment by michalbiesek** [comment]
Hi,
Thank You for your question.

Actually You don't doing nothing wrong with API. 
Maybe it is good idea to distinguish error status in memkind_create_pmem to provide more information than " Unspecified run-time error", ( status MEMKIND_ERROR_RUNTIME ).
I will try to distinguish error status regarding the real issue in memkind_create_pmem operation ( permissions to directory, or invalid path )

**Comment by haraldservat** [comment]
Ok, thanks so much. I think this is sufficient.
