### ISSUE TITLE
memkind_pmtt.c assumes 1:1 map from SRAT proximity domain to NUMA node

### ISSUE THREAD

**Issue by cmcantalupo** [memkind/memkind#13]
On the memkind mailing list Dave Hansen identified that memkind-pmtt makes an assumption of a one to one mapping from SRAT proximity domain to the software defined NUMA node.  This may not be accurate under a variety of system configurations.  Dave's suggested solution is below which uses the SRAT table to get a physical address of each proximity domain and then uses the /sys/devices/system/memory sysfs entries to obtain the physical address ranges for each NUMA node.  

On Mar 17, 2016, at 2:08 PM, Hansen, Dave <dave.hansen@intel.com> wrote:

On 03/17/2016 01:50 PM, Cantalupo, Christopher M wrote:
Do you know of any other way to determine the bandwidth properties of
each of the software defined NUMA nodes?

You have the physical addresses from the SRAT.  You also get a physical
address from memory kobjects:

    /sys/devices/system/memory/memory123/phys_index

The units are in

    /sys/devices/system/memory/block_size_bytes

So:

    # cat /sys/devices/system/memory/block_size_bytes
    80000000
    # cat /sys/devices/system/memory/memory123/phys_index
    0000007b

You can tell that memory123 is at: 0x80000000*0x7b.  There is also a
link to the Linux NUMA node in

    /sys/devices/system/memory/memory123/node1

Which you can use to discern the Linux node numbers.

**Comment by Kkulakowski** [comment]
Memkind no longer uses PMTT-parsing service, so I hope you don't if I close this issue.
