### ISSUE TITLE
How to initialize memkind to a certain pre-allocated state

### ISSUE THREAD

**Issue by fadingsoul** [memkind/memkind#138]
I have a snapshot of memory range on persistent memory, allocated by jemalloc, and I want to reuse the data(address/size recorded in a a separate log) and free space for faster init.
Is there a way to initialize memkind/jemalloc to a certain state instead of a "totally free/clean" state? For the memory address range in my case, I already know that addressX/sizeX, addressY/sizeY and ... contain some data that shouldn't be overwritten unless freed explicitly. How should I tell memkind/jemalloc to mark those memory ranges as occupied and mark the rest of the memory space as free?
I think I can calculate the size_class/run size/run bitmap and page/chunk properties based on the raw inputs listed above. But I don't know the right way/API to inform jemalloc about those information.
And further more, I want do it right(maintainable/portable/general) and fast because I may have a huge memory space to manage and millions of used/free memory ranges. Any hint on the right direction or where I should start will be appreciated. Thank you.

One question, for a certain memory range (mapped from a file on pmem), will memkind create corrupt some of the data(previously allocated by memkind, excluding the jemalloc metadata) on that file? Or is it guaranteed that the data will remain untouched before first call of memkind_malloc? I think my target is feasible only if the data is guaranteed to be untouched. Please let me know if mu understanding is correct.

**Comment by michalbiesek** [comment]
Hi,
Sorry for late response.
Unfortunately there is no way to initialize memkind (pmem kind) to a certain state of data.
PMEM kind supports traditional volatile memory allocation.
What I could suggest is to refer to http://pmem.io/pmdk/ to handle the scenario with allocator which supports persistence.

**Comment by fadingsoul** [comment]
Thanks for the feedback. @michalbiesek

**Comment by lukaszstolarczuk** [comment]
It looks like this issue is answered a long time ago - I'm closing it. If that's not the case, please re-open or just file a new issue.
