### ISSUE TITLE
please use -a when tagging

### ISSUE THREAD

**Issue by kilobyte** [memkind/memkind#143]
You use a mixture of annotated and "lightweight" (ie, unannotated) git tags.  This confuses `git describe`, and those of us who look at its output will think something is wrong.  In this particular case, the tag for **v1.5.0** is annotated while **v1.6.0** and **v1.7.0** are not — this makes git say we're a number of commits past 1.5 while the repo is far after 1.7.

Thus, could you please use `-a` when tagging the next version?

A signed tag (`-s`) would be even better but that requires a gpg key for (within your workflow) little gain.

**Comment by michalbiesek** [comment]
Done (with version 1.8.0 )
