### ISSUE TITLE
Man page update on github.io

### ISSUE THREAD

**Issue by KFilipek** [memkind/memkind#149]
Hi,
There are old manpages, please update.
[URL for man page](http://memkind.github.io/memkind/man_pages/memkind.html)

Regards,
Krzysztof

**Comment by KFilipek** [comment]
@michalbiesek Is it already solved by #150?

**Comment by michalbiesek** [comment]
I think all the comments, which were reported was fixed in #152.
If You have something which was missed please feel free to point it out.
