### ISSUE TITLE
RFC: memkind based on jemalloc 4.x

### ISSUE THREAD

**Issue by krzycz** [memkind/memkind#15]
Some time ago, I requested a new feature in _jemalloc_ - **support for user-defined chunk_alloc_mmap/chunk_alloc_munmap:** https://github.com/jemalloc/jemalloc/issues/201

The original idea has been extended and, thanks to @jasone, it has been eventually implemented in _jemalloc 4.0:_ https://github.com/jemalloc/jemalloc/issues/251

Yet another useful extension introduced in _jemalloc 4.0_ is the support for **explicit thread cache (tcache):** https://github.com/jemalloc/jemalloc/issues/145

It seems like with the above two features we are able to build _memkind_ library on top of the **unmodified (!!!)** _jemalloc._ This [patch](https://github.com/memkind/memkind/compare/dev...krzycz:jemalloc-4.1.0) includes the prototype implementation of _memkind_ library based on _jemalloc 4.1.0._

Looks like the basic functionality is working fine. However, please note that it has not been thoroughly tested. I just ran some basic tests, focusing mostly on PMEM kinds support.

So far, I noticed a couple of issues that need to be solved somehow:
- **A limited number of arenas and thread caches (4095).**
  This might be a problem in case of using multiple memory kinds on the systems with large number of CPU cores (i.e. 256).
  Perhaps the simplest solution would be to extend the _flags_ argument that is passed to mallox() to 64-bit (long long) integer. Another option is to utilize the unused bit in _flags_ to indicate that arena and tcache bits are merged together to encode the 24-bit arena index (implicitly, tcache index is the same as the arena index).
- **Since each arena has its own chunk cache, the chunks allocated by one thread (arena) and later released, cannot be reused by another thread (arena).**
  For memory kinds of limited capacity this may lead to the situation when the entire memory space associated with given kind can be easily and permanently exhausted by one thread.
  This problem is somewhat similar to the following issue: https://github.com/jemalloc/jemalloc/issues/350 
  The difference is that the heap size is not limited by 32-bit address space, but the actual amount of physical memory of given kind installed in the system.
  Obviously, using just one arena per kind is not an option due to performance penalty.
  Presumably, we would need to handle it by implementing some custom chunk dealloc hook, that would actually not deallocate (unmap) chunks, but move them to some global (per-kind) chunk cache, thus making them available for allocation by other threads (arenas).

**Comment by thedrow** [comment]
Does this apply to jemalloc 4.2 as well?

**Comment by lanaczko** [comment]
Jemalloc has been updated.

**Comment by krzycz** [comment]
Well, perhaps the title was a bit misleading, but the key point of this feature was to use **unmodified** jemalloc (which seems to be possible since version 4.0).
Anyway, it was just an RFC including the simple prototype - not the complete solution.
