### ISSUE TITLE
hugepages

### ISSUE THREAD

**Issue by bcernohous** [memkind/memkind#16]
In an older version of memkind, I believe you required pre-configured pools to use hugepages (nr_hugepages)?  

It seems to be working in the latest library with nr_hugepages 0.  I have a v1.0.0 library but haven't yet pulled down the code to check  it out.

Please verify you changed this?  What are you doing now?

**Comment by Kkulakowski** [comment]
Hi,

if it is working with** (/proc/sys/vm/nr_hugepages == 0)** then probably **(/proc/sys/vm/nr_overcommit_hugepages > 0)**. 

As far as I know there is no way to mmap() 2MB page if both of those limits are set to 0.

For more details please read: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt

Regards,
Krzysztof.

**Comment by Kkulakowski** [comment]
@bcernohous: Can I close this issue?

**Comment by bcernohous** [comment]
Yes
