### ISSUE TITLE
memkind_hbw_preferred_hugetlb not on hbw node

### ISSUE THREAD

**Issue by bcernohous** [memkind/memkind#17]
Looking at the memory from malloc'ing hbw_hugetlb and hbw_preferred_hugetlb on SLES12, memkind v.1.0.0, I don't think the preferred is successfully binding to the HBW memory/node?
`
>  memkind_hbw_hugetlb             : is available(yes), total 004236124160, free 004218486784
>                                  : 2aaab6400000 bind:5 file=/anon_hugepage\040(deleted) huge anon=1 dirty=1 N5=1
>                                  : 2aaab6400000-2aaab6800000 rw-p 00000000 00:0d 726057                     /anon_hugepage (deleted)

>  memkind_hbw_preferred_hugetlb   : is available(yes), total 004236124160, free 004216262656
>                                  : 2aaab9800000 prefer:5 file=/anon_hugepage\040(deleted) huge anon=1 dirty=1 N0=1   
`
The first allocation is bind:5 and is bound to N5.   The second is prefer:5 and shows N0?

**Comment by Kkulakowski** [comment]
Is it possible that there were no more available hugepages on preferred node(5)?

If not this might be some kernel issue, if you could provide info about reproduction steps we could try to take a look into that.

**Comment by bcernohous** [comment]
This looked like a kernel issue but I'm not sure we're getting a fix.  Is there a possibility of working around it in the memkind library?

**Comment by Kkulakowski** [comment]
Yes we are planning to take a look into that this sprint, I will get back to you when we will have some update.
