### ISSUE TITLE
build jemalloc with version info

### ISSUE THREAD

**Issue by zhouyuan** [memkind/memkind#177]
Currently the version for jemalloc is marked as 
```
$cat jemalloc/obj/VERSION
0.0.0-0-g0000000000000000000000000000000000000000
```
We should probably point out the version info when building jemalloc. This is more friendly for linking with external applications which may need to check version info of jemalloc.

```
diff --git a/build_jemalloc.sh b/build_jemalloc.sh
index 5d21914..9772ba1 100755
--- a/build_jemalloc.sh
+++ b/build_jemalloc.sh
@@ -29,7 +29,7 @@ test -e configure || autoconf
 test -e obj || mkdir obj
 cd obj
 ../configure --enable-autogen --with-jemalloc-prefix=$JE_PREFIX --without-export \
-             --disable-fill --disable-initial-exec-tls \
+             --with-version=5.0.0-0-g0 --disable-fill --disable-initial-exec-tls \
              $EXTRA_CONF --with-malloc-conf="narenas:256,lg_tcache_max:12"

 make -j`nproc`
```

**Comment by zhouyuan** [comment]
@michalbiesek do you think if this makes sense?
I ran into this issue when try to make Redis to link to jemalloc@memkind, there is a check on the version of jemalloc - the linking failed with "Newer version of jemalloc required"
https://github.com/antirez/redis/blob/unstable/src/zmalloc.h#L48-L56
Please kindly help to take a look when you have time, thanks for the help!

**Comment by michalbiesek** [comment]
@zhouyuan 
Thanks for your message.
Regarding your change, there is one issue with setting version to "5.0.0-0-g0". The jemalloc version under memkind got cherry picked changes from upstream version of jemalloc (5.1.0 to be precise), see commit 53fc92cbfba7b8ccbffb60e97174d555b0beeec4. Need to think about it how handle the correct version number.

**Comment by zhouyuan** [comment]
@michalbiesek thanks for the info! I'm not familiar with memkind, will adding this version info break some features? for Redis case it just needs jemalloc version >2.1 and we could pass an extra param to `update_jemalloc.sh` to do a custom build

Jemalloc suggests a version is mandatory for building 

https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md
```
--with-version=(<major>.<minor>.<bugfix>-<nrev>-g<gid>|VERSION)

The VERSION file is mandatory for successful configuration, and the following steps are taken to assure its presence:

If --with-version=..--g is specified, generate VERSION using the specified value.
If --with-version is not specified in either form and the source directory is inside a git repository, try to generate VERSION via 'git describe' invocations that pattern-match release tags.
If VERSION is missing, generate it with a bogus version: 0.0.0-0-g0000000000000000000000000000000000000000
Note that --with-version=VERSION bypasses (1) and (2), which simplifies VERSION configuration when embedding a jemalloc release into another project's git repository.

```
thanks, -yuan
