### ISSUE TITLE
Memkind doesn't install pkg-config file

### ISSUE THREAD

**Issue by marcinslusarz** [memkind/memkind#204]
Installing memkind with a prefix is currently useless because it's not possible to point other software to find memkind in the directory it was installed to. This is usually achieved by setting the PKG_CONFIG_PATH environment variable, but memkind doesn't support it, because it doesn't provide the pkg-config file.

**Comment by kilobyte** [comment]
Why would you want anything beyond `-L` and `-I`?   There's a lot of insanity in building memkind, but once it's built, it's a regular library that requires no special handling.

**Comment by michalbiesek** [comment]
@marcinslusarz 
Please let me know if it works as you expect it, so the issue could be possibly closed.

**Comment by marcinslusarz** [comment]
It works now. Thanks!
