### ISSUE TITLE
Are hbw_malloc() and hbw_free() thread safe?

### ISSUE THREAD

**Issue by BamboWu** [memkind/memkind#213]
I am using `hbw_malloc()` and `hbw_free()` for parallel graph processing applications, and observe severe memory leakage.

The program use pthread library to create 2 master threads, which create 32 threads per master threads.
The 2 master threads use `hbw_malloc()` to get space to store local copies of the graph before the 64 subworker threads are created.
After the 64 subworker threads are joined, the 2 master threads then release the memory by `hbw_free()`.
The graph processing has short duration (1~5 seconds), so to reduce the effect of variation, I make a `for` loop to repeatedly create master threads and join them many many times.
If it loops too many repetitions, a segmentation fault occurs.
So I monitored the memory usage by `top`, and find the memory usage keeps increasing every repetition.

And it seems if I replace `hbw_malloc()` with `malloc()`, `hbw_free()` with `free()`, there is no such obvious memory leakage.

I am wondering how the memory leaks.
`hbw_malloc()` and `hbw_free()` should support multi-thread, right?

Thank in advance!

**Comment by michalbiesek** [comment]
Hi,
Sorry for late response. HBW API which you mention should be thread-safe.
Which version of memkind do you use? If it is possible please share the code to reproduce this issue.

**Comment by lukaszstolarczuk** [comment]
It looks like the issue has been stale for a while. I allow myself to close this one. If you feel like continuing discussion here, please just re-open it or file a new issue.
