### ISSUE TITLE
Not set MEMKIND_HBW_NODES causes segmentation fault

### ISSUE THREAD

**Issue by KFilipek** [memkind/memkind#219]
Hi,
Can we add some diagnostics to handle not initialized HBW environment variable (MEMKIND_HBW_NODES) on not supported CPUs?
memkind_malloc(MEMKIND_HBW, 1024); will fail.
My proposition is to add some log_err to memkind_hbw_closest_numanode_init() inside memkind_hbw.c file.

Best regards,
Krzysztof Filipek

**Comment by michalbiesek** [comment]
Fixed in release v1.10.0
