### ISSUE TITLE
pmem_extent_dalloc leaks

### ISSUE THREAD

**Issue by JohnSully** [memkind/memkind#221]
If jemalloc ever decides to return space to the system memkind will simply unmap it and leak it.  I have a local version that resolves this with FALLOC_FL_PUNCH_HOLE, but it seems until this resolved memkind_pmem isn't suitable for production software.

There are a few options: 
Use the punch hole method which limits the supported filesystems or track the extents manually and never return space to the filesystem.

**Comment by pbalcer** [comment]
```
    if (madvise(addr, size, MADV_REMOVE) != 0 && errno != EOPNOTSUPP) {
        if (munmap(addr, size) == -1) {
            log_err("munmap failed!");
        }
    }
```
This code calls madvise with MADV_REMOVE which, quoting `madvise(2)`, will:
> Free up a given range of pages and its associated backing store.
> This is equivalent to punching a hole in the corresponding byte
> range  of  the  backing  store  (see  fallocate(2)).  Subsequent
> accesses in the specified address range will see bytes  containing zero.

Only if that fails, it resorts to `unmap`. This is probably unnecessary and we should probably fail loudly with a message that the filesystem must support hole punching.

**Comment by JohnSully** [comment]
Hmm, I could have sworn I repro'd it not giving memory back, but I just tested now and it does indeed.  It was about 6 months ago so who knows.  Sorry for my aggressive phrasing.

**Comment by pbalcer** [comment]
Might have been a kernel bug.
No worries, we appreciate the interest.
