### ISSUE TITLE
What if I use malloc while using mankind_malloc? Does malloc allocate memory to PMEM？

### ISSUE THREAD

**Issue by LiunxPaisley** [memkind/memkind#258]
Hi, I'm programming on a machine with a Intel 3D XPoint memory (PMEM). I'm wondering that what will happen if I use `mankind_malloc()` to allocate memory on PMEM while use `malloc()` to allocate standard memory on DRAM? Will `malloc()` allocate memory on PMEM too?

**Comment by michalbiesek** [comment]
If you use `malloc()` it will allocate memory in standard memory on DRAM.
For allocation on DRAM you could also use `memkind_malloc()` with kind define as `MEMKIND_DEFAULT`

**Comment by LiunxPaisley** [comment]
Thanks for the response. @michalbiesek
