### ISSUE TITLE
hbw::allocator lacks operator== and operator!=

### ISSUE THREAD

**Issue by camaclean** [memkind/memkind#26]
hbw_allocator.h lacks definitions for operator== and operator!=. This is causing copy constructing of std::vector<T,hbw::allocator<T>> to fail for me.

**Comment by Kkulakowski** [comment]
Thank you for your submission.

Could you verify that [this patch](https://github.com/memkind/memkind/pull/27) is fixing your issue? If not could you provide reproduction steps (sample code, and compiler info would be appreciated).

Regards,
Krzysztof.
