### ISSUE TITLE
The offset cannot track the wholes in the pmem_extent_dalloc(MADV_REMOVE) and cause the usable space shrink

### ISSUE THREAD

**Issue by chris-yupeng** [memkind/memkind#274]
Hi,
I have read about the memkind_pmem.c and I think during the pmem_extent_dalloc, the MADV_REMOVE has removed the space both in the memory and filesystem. So there would be holes in the file. 
But in the memkind_pmem_mmap, it uses the offset to manage the size the extents allocated , which I think it would shrink the usable space.
Suppose the max_size is 100GB, and as the allocation goes on, the extent dalloc has removed 30GB using MADV_REMOVE. That means actually only 70GB is used. But we cannot allocate any more, because the offset is 100GB.
So I think it's better to use some kind of mapped space to track the space those extents allocated.  

Thanks,
Chris Yu

**Comment by pbalcer** [comment]
That's not entirely true. While you are right that memkind uses simple file offsets to allocate new memory extents, and that *does* make the file larger, it's not a problem on file systems that support sparse files - so pretty much all of the ones we care about (ext4, xfs).

The actual physical space is deallocated during MADV_REMOVE, and that space can be reused later on, no matter at what offset in the file. And so there's no need to track where the holes are in the file.

The only reason why you would want to track the correlation between file offsets and virtual mappings is when you don't want to use the file system to manage that. This might have some performance benefit, but it would be relatively complex.

**Comment by chris-yupeng** [comment]
Hi pbalcer,
Thanks for the reply.
I am still a little puzzled. I think I understand that the physical space deallocated during MADV_REMOVE can be re-used by file system later on (maybe just add an entry in the inode pointing to the deallocated block) during fallocate. But when the fallocate re-use that space, the offset in the memkind_pmem_mmap would take that space into account again even it's a re-use space, right?
For example, I have a 500GB PMEM device in fsdax mode. And I want to create a pool using memkind in size of 100GB.  For the other 400GB I have other plans, so I don't want to use more than 100GB. I don't care if the addresses allocated from the pool is contiguous or not.  
After some running, I have allocated like 99GB, and the priv->offset is at 99GB. Then I free 50GB space. However, the priv->offset is still at 99GB, but actually only 49GB physical space is used right now.  Then I want to allocate 5GB, it would fail as it would check (size_t)priv->offset + size > priv->max_size (99GB+5GB > 100GB) in the memkind_pmem_mmap. But since those 50GB is already returned to the os, we actually can have 51GB to use. So that's why I think priv->offset might not be proper in this case.
Please correct me if I mistaken something. 

Thanks,
Chris Yu

**Comment by pbalcer** [comment]
You are absolutely right! Thanks for pointing this out.
The problem here is that we treat the `offset` variable to indicate the occupied physical space, which is wrong. We should have a separate counter that sums up all the allocations and deallocations, and make a decision to return ENOMEM based on that, instead of the offset.

**Comment by michalbiesek** [comment]
Fixed in release v1.10.0
