### ISSUE TITLE
memkind-pmtt  stop nuking sysconfdir and contents

### ISSUE THREAD

**Issue by aquini** [memkind/memkind#3]
Hi,
I'm working on getting memkind officially packaged in RPM for Fedora and EPEL package collections and I stumbled across a minor issue where memkind-pmtt tool is deliberately nuking /etc/memkind (sysconfdir) and it's content in case of not being able to parse its expected system's acpi tables. In order to avoid overlapping RPM's ownership of the default sysconfdir for the package, as well as to avoid crazy link/unlink dances around the default MEMKIND_BANDWIDTH_PATH file, I'm proposing the following patch:

https://lists.01.org/pipermail/memkind/2015-May/000009.html

Regards,
-- Rafael

**Comment by Kkulakowski** [comment]
Hi Rafael,

I was looking into your code, and I find out that there are few issues with our code (not introduced by your change, but i believe it is good time to fix them now).

First of all, if we want "/etc/memkind" to be deleted by rpm manager, we need to specify it in %files section of rpm spec (which should be done anyway). The only question is, if we want to keep in repository directory with empty "node-bandwidth" file, or if it is better idea to create it during rpm creation process.

Another thing is that current logic of "init.d/memkind" is vulnerable for scenarios where system wasn't turned off properly (power off, hard reset, etc.). So I believe that start() should begin with check for existence of node-bandwidth file, and eventually delete it.

I'm working on branch with those improvements, and I'll notify you when I finish, but if you have any suggestions I'll be glad to hear them.

Best Regards,
Krzysztof.

**Comment by aquini** [comment]
On Mon, May 18, 2015 at 09:33:36AM -0700, Krzysztof Kułakowski wrote:
>    Hi Rafael,
> 
>    I was looking into your code, and I find out that there are few issues
>    with our code (not introduced by your change, but i believe it is good
>    time to fix them now).
> 
>    First of all, if we want "/etc/memkind" to be deleted by rpm manager,
>    we need to specify it in %files section of rpm spec (which should be
>    done anyway). The only question is, if we want to keep in repository
>    directory with empty "node-bandwidth" file, or if it is better idea to
>    create it during rpm creation process.
> 
Nice catch. I filed this issue and suggested that patch to have the
required artifacts to patch source files as far as Fedora Packaging
guidelines are concerned -- Here's the memkind.spec file that strictly
follows the Fedora Packaging Guidelines:
   https://aquini.fedorapeople.org/memkind/memkind.spec

Since we have a tool that generates node-bandwidth file upon demand, I
really don't see why we shouldn't call it in RPM's %post section from
the spec file (although I'm doing it in that Fedora spec deliberatadely)



>    Another thing is that current logic of "init.d/memkind" is vulnerable
>    for scenarios where system wasn't turned off properly (power off, hard
>    reset, etc.). So I believe that start() should begin with check for
>    existence of node-bandwidth file, and eventually delete it.
>
For the same reason explained above (we have a tool that's capable of
creating dependency configuration files on-demand) plus the fact that
newer Fedora and EPEL distro, by default, do not use SysV init scripts
anymore, I'd be more likely to suggest getting rid of that init script
completely -- In this early addition to Fedora/EPEL repositories, for the
initial testing phase of that package, I'm not intending to use that 
SysV init script at all.



>    I'm working on branch with those improvements, and I'll notify you when
>    I finish, but if you have any suggestions I'll be glad to hear them.
> 
I'll be glad to help on reviewing your work, as well!

Thanks for the feedback and heads-up!
-- Rafael

**Comment by Kkulakowski** [comment]
Hi,

i finished my change. That's what I done:
- "/etc/memkind" dir, and "/etc/memkind/node-bandwidth" added to %files section of rpm spec (to achieve that, I added placeholder file to "memkind/config/node-bandwidth")
- "memkind/init.d/memkind" start() will now check for existence of /etc/memkind/node-bandwidth, and delete it if necessary (this let us avoid issues with leftovers, if system was not turned off correctly)

In subject of generating node-bandwidth file. I'm generally agree that current solution is imperfect. The case is that those values can change after system reboot, and this file should reflect that change. I have strong feeling that expecting from user to update that manually every time, may be inconvenient and error-prone.

As I understand Fedora start using systemd instead of SysV init. Do you think that moving this logic to systemd would be ok? 

and here is diff (including your changes):
```diff
diff --git a/Makefile.am b/Makefile.am
index f51453a..5cefdd9 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -63,6 +63,7 @@ memkind_pmtt_LDADD = libmemkind.la
 
 EXTRA_DIST = autogen.sh \
              init.d/memkind \
+             config/node-bandwidth \
              gtest-1.7.0.zip \
              examples/README \
              test/check.sh \
diff --git a/config/node-bandwidth b/config/node-bandwidth
new file mode 100644
index 0000000..e6ddd6d
--- /dev/null
+++ b/config/node-bandwidth
@@ -0,0 +1,5 @@
+################################################################################
+#                                                                              #
+# This file is intentionaly left blank, as placeholder for node-bandwidth file #
+#                                                                              #
+################################################################################
diff --git a/init.d/memkind b/init.d/memkind
index 1be0954..cffb15f 100755
--- a/init.d/memkind
+++ b/init.d/memkind
@@ -73,13 +73,21 @@ MEMKIND_BIN=/usr/sbin/memkind-pmtt
 
 start() {
     echo_success "creating bandwidth values file"
-    $MEMKIND_BIN
-    err=$?
-    if [ $err -eq 0 ] && [ -f $MEMKIND_FILE ]
-    then
-        echo_success "created file: $MEMKIND_FILE"
-    else
-        echo_failure "could not create file: $MEMKIND_FILE"
+    if [ -f $MEMKIND_FILE ]; then
+        echo_success "bandwidth values file exists, atemptting to delete before
+        creation."
+        stop
+    fi
+
+    if [ ! -f $MEMKIND_FILE ]; then
+        $MEMKIND_BIN
+        err=$?
+        if [ $err -eq 0 ] && [ -f $MEMKIND_FILE ]
+        then
+            echo_success "created file: $MEMKIND_FILE"
+        else
+            echo_failure "could not create file: $MEMKIND_FILE"
+        fi
     fi
 }
 
@@ -90,14 +98,6 @@ stop() {
     if [ $err -eq 0 ] && [ ! -f $MEMKIND_FILE ]
     then
         echo_success "deleted file: $MEMKIND_FILE"
-        rmdir $MEMKIND_DIR
-        err=$?
-        if [ $err -eq 0 ] && [ ! -d $MEMKIND_DIR ]
-        then
-            echo_success "deleted directory: $MEMKIND_DIR"
-        else
-            echo_failure "could not delete directory: $MEMKIND_DIR"
-        fi
     else
         echo_failure "could not delete file: $MEMKIND_FILE"
     fi
diff --git a/memkind.spec.mk b/memkind.spec.mk
index e5df783..fa9c6b7 100644
--- a/memkind.spec.mk
+++ b/memkind.spec.mk
@@ -66,6 +66,8 @@ Prefix: %{_initddir}
 %define docdir %{_defaultdocdir}/memkind-%{version}
 %endif
 
+%define confdir %{_sysconfdir}/memkind
+
 %description
 The memkind library is a user extensible heap manager built on top of
 jemalloc which enables control of memory characteristics and a
@@ -126,6 +128,8 @@ $(make_prefix)%{__make} $(make_postfix)
 %{__make} DESTDIR=%{buildroot} install
 %{__install} -d %{buildroot}/%{_initddir}
 %{__install} init.d/memkind %{buildroot}/%{_initddir}/memkind
+%{__install} -d %{buildroot}/%{confdir}
+%{__install} config/node-bandwidth %{buildroot}/%{confdir}/node-bandwidth
 rm -f %{buildroot}/%{_libdir}/libmemkind.a
 rm -f %{buildroot}/%{_libdir}/libmemkind.la
 rm -f %{buildroot}/%{_libdir}/libnumakind.*
@@ -182,6 +186,8 @@ fi
 %{_bindir}/memkind-hbw-nodes
 %{_sbindir}/memkind-pmtt
 %{_initddir}/memkind
+%{confdir}/node-bandwidth
+%dir %{confdir}
 %dir %{docdir}
 %doc %{docdir}/README
 %doc %{docdir}/COPYING
diff --git a/src/memkind_pmtt.c b/src/memkind_pmtt.c
index ebabafd..9d9296c 100644
--- a/src/memkind_pmtt.c
+++ b/src/memkind_pmtt.c
@@ -220,7 +220,6 @@ int memkind_pmtt(char *pmtt_path, char *bandwidth_path)
         err = errno ? -errno : 1;
         goto exit;
     }
-    unlink(bandwidth_path);
     fd = open(bandwidth_path, O_CREAT | O_EXCL | O_WRONLY, 0644);
     if (fd == -1) {
         fprintf(stderr, "ERROR: <memkind_pmtt> opening %s for writing\n", bandwidth_path);
@@ -252,12 +251,6 @@ exit:
     if (bandwidth != NULL) {
         free(bandwidth);
     }
-    if (err) {
-        unlink(bandwidth_path);
-        if(*dir) {
-            rmdir(dir);
-        }
-    }
     return err;
 }
```

Best Regards,
Krzysztof.

**Comment by Kkulakowski** [comment]
Hi Rafael,

today we pushed bunched of commits, including your patch. I hope that this will satisfy your expectations, and meet fedora criteria. Please feel free to review current codebase, and let us know if there are any other issues.

Big thanks for your contribution!

PS: If there will be no update in this thread I hope you dont mind if I close this issue.

**Comment by cmcantalupo** [comment]
This issue is resolved by commit
b26b870cae25d2c72c55e30821a47ac5dfd55413
