### ISSUE TITLE
build failure with gcc-10

### ISSUE THREAD

**Issue by kilobyte** [memkind/memkind#317]
When building with gcc-10 (gcc-9 is ok):
```
In file included from examples/memkind_cpp_allocator.cpp:34:
./include/memkind_allocator.h: In constructor ‘libmemkind::static_kind::allocator<T>::allocator(libmemkind::kinds)’:
./include/memkind_allocator.h:144:36: error: ‘runtime_error’ is not a member of ‘std’
  144 |                         throw std::runtime_error("Unkown libmemkind::kinds");
      |                                    ^~~~~~~~~~~~~
```

**Comment by michalbiesek** [comment]
As we spoke offline gcc-10 is not yet officially released so I treat the status above as ambiguous.

**Comment by lukaszstolarczuk** [comment]
I just encountered this issue while building memkind on archlinux-base-latest in my PR's build (archlinux is not regularly build in our CI).
https://travis-ci.org/github/pmem/pmemkv/jobs/716964796

I found somewhere that perhaps `#include <stdexcept>` will be a solution to that problem.

**Comment by michalbiesek** [comment]
> I just encountered this issue while building memkind on archlinux-base-latest in my PR's build (archlinux is not regularly build in our CI).
> https://travis-ci.org/github/pmem/pmemkv/jobs/716964796
> 
> I found somewhere that perhaps `#include <stdexcept>` will be a solution to that problem.

https://github.com/memkind/memkind/commit/315cf59133eca7795cb55c178dfb886f50b4e87a
The fix will be available in next release
