### ISSUE TITLE
Mac: Unsupported malloc zone version

### ISSUE THREAD

**Issue by jeffhammond** [memkind/memkind#32]
When I compile on Mac, none of the tested malloc zone sizes are valid.  I can build the official version of JEMalloc just fine, so this appears to be a bug in the Memkind fork.

[config.log.txt](https://github.com/memkind/memkind/files/500743/config.log.txt)

**Comment by Kkulakowski** [comment]
Hi Jeff,

My answer here will be fairly similar to #33, we could try looking into that, although I don't have access to hardware were I can reproduce your issue, and I'm not sure if there is any value in supporting OS X.

We would be glad to take pull request if you mind to provide one.

Regards,
Krzysztof.

**Comment by jeffhammond** [comment]
I think the solution here is to rebase the JEMalloc included in Memkind with a more recent one that supports Mac.  How feasible is that?

**Comment by Kkulakowski** [comment]
We are planning to do that, although it's hard to provide precise estimate right now. I'll keep you posted when it happens.
