### ISSUE TITLE
nproc is not a command on Mac

### ISSUE THREAD

**Issue by jeffhammond** [memkind/memkind#33]
```
./build_jemalloc.sh: line 33: nproc: command not found
```

Perhaps a better choice in the `build_jemalloc.sh` script is `make -l`.

**Comment by Kkulakowski** [comment]
Hi Jeff,

thanks for submitting  this issue.

I tried "make -l" and it seems that no matter what value I'll provide I'm getting "make -l" taking 3-4 times longer comparing to "make -j `nproc`" (in absolute numbers it's difference from 1.5 s to 5.5 s). 

Well, maybe it's not a big deal, I just wonder: do you think that making memkind build-able on OS X make any sense? Right now I don't have any machine where I could validate potential build blockers on OS X, so I would like to know if it is worth effort.

Regards,
Krzysztof.

**Comment by jeffhammond** [comment]
I should have been more clear.  `make -l` takes an argument just like `make -j`.

Unfortunately, determining the arguments requires the same information, the load option doesn't help much.

I'll create a separate issues for Mac so we can discuss it explicitly.

**Comment by akimd** [comment]
FTR `sysctl -n hw.physicalcpu` is the equivalent to `nproc` on macOS.

**Comment by ApatheticsAnonymous** [comment]
> FTR `sysctl -n hw.physicalcpu` is the equivalent to `nproc` on macOS.

`nproc` returns logical cores. The mac equivalent of that is `sysctl -n hw.logicalcpu`

**Comment by judge2020** [comment]
An alias for local development:
```
alias nproc="sysctl -n hw.logicalcpu"
```
Note: don't use `--all` with this, it will break.

**Comment by liudonghua123** [comment]
I use `make -j$(getconf _NPROCESSORS_ONLN)`. 

And for github macos runner, they are the same.

```
macos: sysctl -n hw.physicalcpu: 4
macos: getconf _NPROCESSORS_ONLN: 4
```

**Comment by inlann** [comment]
`brew install coreutils`
