### ISSUE TITLE
Attempting Inter-process communication on HBW numa nodes

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [memkind/memkind#35]
_This is a re-post of a thread from Intel developer zone forum (https://software.intel.com/en-us/forums/intel-many-integrated-core/topic/698542). My apologies if you saw that as well_

Hello,

I wanted to check if lib memkind has options to realize operations such as mmap to get inter-process communication to work between 2 processes on the same KNL node but with memory being mapped on MCDRAM instead of DRAM. I didn't find this in the examples directory of memkind github repo. Please let me know if you have any pointers/suggestions. Thanks in advance.

**Comment by Kkulakowski** [comment]
Hi,

sorry for late response.  There is no such option, nor plans to add it at the moment.

Best Regards,
Krzysztof.
