### ISSUE TITLE
Determine if a pointer is in hbwmalloc's/memkind's space?

### ISSUE THREAD

**Issue by dmk42** [memkind/memkind#38]
There are certain complicated situations where I need to keep the current allocator in place for normal memory, and augment it with hbwmalloc for MCDRAM.  However, a problem arises when I need to do a free.  I would really like to have a way to tell if a pointer is within hbwmalloc's managed space, so I know which free to call.  Right now, the only way I see to do this is in memkind's private API, not exported to users (check_addr).  Can we get some kind of check_addr-like functionality for public use?

**Comment by Kkulakowski** [comment]
Hi David,

unfortunately answer is "no".

Heap managers do not provide such feature and there are strong performance arguments behind it. check_addr() example you mentioned is relevant only to special way memkind handles gigabyte pages, but this will be removed soon.

In C++ you could use allocator class we provide in hbw_allocator.h to manage memory allocations and freeing for you.

In plain C I would suggest is to keep allocator information along with pointer to allocated memory, e.g. by using something like:
struct allocation {
   void* ptr;
   int allocator;
}
such struct should be easy to cast to/from void* and might be used to determine which free should be called when memory needs to be released.

Regards,
Krzysztof.

**Comment by lanaczko** [comment]
Hi David,
Does Krzysztof answer addresses your needs? I'd like to close this issue.

Thanks,
Lukasz

**Comment by dmk42** [comment]
Lukasz,

It doesn't help me, but I found another way to do it.  Instead of inquiring whether a pointer is in the arena or not, I used hwloc to determine whether the pointer is in MCDRAM or not.

David

**Comment by Kkulakowski** [comment]
Hi David,

if verification whether pointer is in the MCDRAM or not is enough for you, then you don't even need hwloc. In hbwmalloc.h there is a fucntion "hbw_verify_memory_region()" which does exactly that. 

Regards,
Krzysztof.

**Comment by dmk42** [comment]
Thanks.  It turns out that hwloc is already being used by other parts of our code, and our system's memkind is too old to include hbw_verity_memory_region\(\).  However, that looks like a better way to go after our system is updated to a more recent version.

David
