### ISSUE TITLE
Adjust memkind's configure.ac to get rid of obsolete m4 macros

### ISSUE THREAD

**Issue by aquini** [memkind/memkind#4]
Yet on the work to get memkind packaged for Fedora, we need to get rid of obsolete M4 macros, to avoid potential build issues in the future: https://fedorahosted.org/FedoraReview/wiki/AutoTools
I've sent a patch to the mailing list addressing this another minor issue wrt Fedora Packaging Guidelines:
https://lists.01.org/pipermail/memkind/2015-May/000011.html

-- Rafael

**Comment by Kkulakowski** [comment]
Hi Rafael,

I don't want to copy paste my response from https://github.com/memkind/memkind/issues/3, but last drop also including this patch. It was absolutely fine just how you sent it, but if there is anything you want to add we will be glad to hear you voice! :)

Again, thank you, we really appreciate effort you put in this contribution!

Best Regards,
Krzysztof.

**Comment by cmcantalupo** [comment]
This issue is resolved by commit
a4c7a138ba4027dee94dd97dfd489897dbf7fa81
