### ISSUE TITLE
Library hangs when deallocating memory

### ISSUE THREAD

**Issue by fedorova** [memkind/memkind#403]
A number of benchmarks I am running hang in madvise with the following call stack when I try to free memory on Optane via libmemkind. The CPU is used at 100%, so this appears to be some kind of infinite loop.

#0  0x00007feb04c87a4b in madvise () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007feb04d6f2ae in pmem_extent_dalloc (extent_hooks=<optimized out>, committed=<optimized out>, arena_ind=505, size=32768, 
    addr=0x7fca932b4000) at src/memkind_pmem.c:89
#2  pmem_extent_dalloc (extent_hooks=<optimized out>, addr=0x7fca932b4000, size=32768, committed=<optimized out>, arena_ind=505)
    at src/memkind_pmem.c:74
#3  0x00007feb04db7a95 in extent_dalloc_wrapper_try (extent=0x7fe660162440, r_extent_hooks=0x7ffd4a0add40, arena=0x7feae40008c0, 
    tsdn=0x7feb0482c778) at include/jemalloc/internal/extent_inlines.h:141
#4  je_extent_dalloc_wrapper (tsdn=tsdn@entry=0x7feb0482c778, arena=arena@entry=0x7feae40008c0, 
    r_extent_hooks=r_extent_hooks@entry=0x7ffd4a0add40, extent=extent@entry=0x7fe660162440) at src/extent.c:1820
#5  0x00007feb04d7daea in arena_decay_stashed (is_background_thread=<optimized out>, decay_extents=<synthetic pointer>, 
    all=<optimized out>, extents=0x7feae40031a8, decay=0x7feae4006be0, r_extent_hooks=0x7ffd4a0add40, arena=0x7feae40008c0, 
    tsdn=0x7feb0482c778) at src/arena.c:880
#6  arena_decay_to_limit (tsdn=tsdn@entry=0x7feb0482c778, arena=arena@entry=0x7feae40008c0, decay=decay@entry=0x7feae4006be0, 
    extents=extents@entry=0x7feae40031a8, all=all@entry=false, npages_limit=<optimized out>, npages_decay_max=<optimized out>, 
    is_background_thread=<optimized out>) at src/arena.c:937
#7  0x00007feb04d7de33 in arena_decay_try_purge (is_background_thread=<optimized out>, npages_limit=<optimized out>, 
    current_npages=<optimized out>, extents=<optimized out>, decay=<optimized out>, arena=<optimized out>, tsdn=<optimized out>)
    at src/arena.c:722
#8  arena_decay_try_purge (is_background_thread=<optimized out>, npages_limit=<optimized out>, current_npages=<optimized out>, 
    extents=<optimized out>, decay=<optimized out>, arena=<optimized out>, tsdn=<optimized out>) at src/arena.c:611
#9  arena_maybe_decay (is_background_thread=<optimized out>, extents=<optimized out>, decay=<optimized out>, arena=<optimized out>, 
    tsdn=<optimized out>) at src/arena.c:762
#10 arena_maybe_decay (tsdn=0x7feb0482c778, arena=0x7feae40008c0, decay=0x7feae4006be0, extents=0x7feae40031a8, 
    is_background_thread=<optimized out>) at src/arena.c:714
#11 0x00007feb04d8043c in arena_decay_impl (all=<optimized out>, is_background_thread=false, extents=0x7feae40031a8, 
    decay=0x7feae4006be0, arena=0x7feae40008c0, tsdn=0x7feb0482c778) at src/arena.c:964
#12 arena_decay_dirty (all=<optimized out>, is_background_thread=false, arena=0x7feae40008c0, tsdn=0x7feb0482c778) at src/arena.c:985
#13 je_arena_decay (tsdn=0x7feb0482c778, arena=0x7feae40008c0, is_background_thread=false, all=<optimized out>) at src/arena.c:998
#14 0x00007feb04dbc80f in arena_decay_ticks (nticks=1, arena=0x7feae40008c0, tsdn=0x7feb0482c778)
    at include/jemalloc/internal/arena_inlines_b.h:126
#15 arena_decay_tick (arena=0x7feae40008c0, tsdn=0x7feb0482c778) at include/jemalloc/internal/arena_inlines_b.h:135
#16 je_large_dalloc (tsdn=tsdn@entry=0x7feb0482c778, extent=<optimized out>) at src/large.c:364
#17 0x00007feb04d70513 in arena_dalloc_large_no_tcache (szind=<optimized out>, ptr=<optimized out>, tsdn=0x7feb0482c778)
    at include/jemalloc/internal/arena_inlines_b.h:237
#18 arena_dalloc_no_tcache (tsdn=0x7feb0482c778, ptr=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:265
#19 0x00007feb04d7bc2b in arena_dalloc (slow_path=<optimized out>, alloc_ctx=<optimized out>, tcache=<optimized out>, 
    ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:292
#20 idalloctm (slow_path=<optimized out>, is_internal=<optimized out>, alloc_ctx=<optimized out>, tcache=<optimized out>, 
    ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#21 ifree (slow_path=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsd=<optimized out>) at src/jemalloc.c:2589
#22 jemk_dallocx (ptr=ptr@entry=0x7fd4f9e35140, flags=<optimized out>) at src/jemalloc.c:3526
#23 0x00007feb04d6c747 in memkind_arena_free (ptr=0x7fd4f9e35140, kind=<optimized out>) at src/memkind_arena.c:479
#24 memkind_arena_free (kind=<optimized out>, ptr=0x7fd4f9e35140) at src/memkind_arena.c:510
#25 0x0000557ff6787e0c in __wt_blkcache_free (ptr=<optimized out>, session=0x7feae2ee5010) at ../src/block/block_cache.c:56
#26 __wt_block_cache_destroy (session=session@entry=0x7feae2ee5010) at ../src/block/block_cache.c:370
#27 0x0000557ff66d9504 in __wt_connection_close (conn=conn@entry=0x557ff863cc40) at ../src/conn/conn_open.c:90
#28 0x0000557ff66cdad0 in __conn_close (wt_conn=0x557ff863cc40, config=<optimized out>) at ../src/conn/conn_api.c:1100
#29 0x0000557ff66c1b5e in start_run (wtperf=0x7ffd4a0ae510) at ../../../bench/wtperf/wtperf.c:2494
#30 0x0000557ff66b9791 in start_all_runs (wtperf=0x7ffd4a0ae510) at ../../../bench/wtperf/wtperf.c:2311
#31 main (argc=<optimized out>, argv=<optimized out>) at ../../../bench/wtperf/wtperf.c:2797

**Comment by michalbiesek** [comment]
We resolve the issue offline. The main culprit here was a madvise call.
After update to the official version of memkind [v1.10.1](https://github.com/memkind/memkind/releases/tag/v1.10.1) and use the MEMKIND_HOG_MEMORY variable, the madvise call was removed.
@fedorova 
Feel free to close this issue, or if you have more comments, please post it here.
