### ISSUE TITLE
Add interleave variant of MEMKIND_DAX_KMEM

### ISSUE THREAD

**Issue by eberroca** [memkind/memkind#416]
Memkind overwrites the process-wide memory policy set through numactl. However, memkind is missing the interleave variant. It would be nice to have it on KMEM-DAX.

**Comment by michalbiesek** [comment]
FYI We merge the change with an interleave variant of KMEM_DAX on a master branch - the function would be available in the next release, but the master branch is stable so that you could check this functionality on it as well.

**Comment by eberroca** [comment]
ok, thanks !

**Comment by michalbiesek** [comment]
The functionality is available in https://github.com/memkind/memkind/releases/tag/v1.11.0
