### ISSUE TITLE
Allow to specify jemalloc library path when building memkind

### ISSUE THREAD

**Issue by thedrow** [memkind/memkind#46]
The project I'm linking memkind into already uses jemalloc. I'd like to skip building jemalloc again and simply link to the already built library.

**Comment by lanaczko** [comment]
Hi Omer!

Thank you for interest in memkind.
For my curiosity - what's your use case for memkind?
As for using prebuilt jemalloc - this is a low value for us, but you are welcome to develop patch(es) yourself and send it for review&acceptance.
There are two things to consider/look for:
1) memkind statically links with jemalloc
2) memkind utilizes jemalloc's configure options that puts prefix before jemalloc's symbols (i.e. --with-jemalloc-prefix=jemk_).

Let me know your thoughts.

**Comment by thedrow** [comment]
I'm trying to integrate memkind with RethinkDB in order to make the page cache query aware.
RethinkDB already uses jemalloc 4.5.0 without a prefix. RethinkDB already links with jemalloc statically.
I'd like to share the same linkage with both.
I'm not very good with autotools so a patch might take awhile. If you can beat me to it, ping me.

**Comment by lanaczko** [comment]
What hardware are you using? Please note, that memkind makes most sense in heterogeneous memory configurations (e.g. Intel Xeon Phi x200 codenamed Knights Landing, with additional 16GB on-package RAM).

BTW, recent commit allows for specifying jemalloc's prefix at compile time (including empty one); https://github.com/memkind/memkind/commit/76f9ebdfe1ecef3ef777e3f03ffd1591fadd55e1

**Comment by lukaszstolarczuk** [comment]
This issue looks a bit old-ish, with no more interest (since 17'). I'm assuming the priority isn't the highest one. I'm allowing myself to close it. If you feel like continuing, please just re-open it or file a new issue.
