### ISSUE TITLE
Compile problems with older platforms

### ISSUE THREAD

**Issue by mark-mb** [memkind/memkind#48]
I was trying to compile memkind in a platform with a bit outdated software and I found some issues:
 - Function [`numa_bitmask_weight`](https://github.com/memkind/memkind/tree/master/src#L43) is present starting in libnuma versions [2.0.9](https://github.com/numactl/numactl/commit/9848be9c4c23c132de5ac07837057a3b31f633c0) and newer. It would be interesting to allow the use of a custom libnuma installation on configure.ac, so it can use a local installation instead of the (old) system one.
 - Function `clock_gettime` is not linked by default in older versions of glib. From the man page: "Link with -lrt (only for glibc versions before 2.17)". It would be interesting to check for this dependence in configure.ac

I can fix it locally with:
`./configure --prefix=<install-path> CPPFLAGS=-I<numa-install-path>/include LDFLAGS="-L<numa-install-path>/lib -lrt"`

But it would be nice if you considered those changes, for people in the same situation as I am.

**Comment by yanxianrui** [comment]
> I was trying to compile memkind in a platform with a bit outdated software and I found some issues:
> 
> * Function [`numa_bitmask_weight`](https://github.com/memkind/memkind/tree/master/src#L43) is present starting in libnuma versions [2.0.9](https://github.com/numactl/numactl/commit/9848be9c4c23c132de5ac07837057a3b31f633c0) and newer. It would be interesting to allow the use of a custom libnuma installation on configure.ac, so it can use a local installation instead of the (old) system one.
> * Function `clock_gettime` is not linked by default in older versions of glib. From the man page: "Link with -lrt (only for glibc versions before 2.17)". It would be interesting to check for this dependence in configure.ac
> 
> I can fix it locally with:
> `./configure --prefix=<install-path> CPPFLAGS=-I<numa-install-path>/include LDFLAGS="-L<numa-install-path>/lib -lrt"`
> 
> But it would be nice if you considered those changes, for people in the same situation as I am.

Hello @mark-mb 
I experience same problem with libnuma.  May I known how you install libnuma? my system is ubuntu12.04 and I can't find some newer numa package suite it.   
Thanks for any reply.

**Comment by kilobyte** [comment]
This is an old bug; since then, Ubuntu 12.04 has gone out of support (even extended).  The oldest supported distribution, CentOS/RHEL 7, has glibc 2.17 which has clock_gettime built in.

Likewise, libnuma 2.0.9 is present in Ubuntu 14.04 and RHEL 7.
