### ISSUE TITLE
Wrong allocation node when using MEMKIND_HBW in system with multiple sockets 

### ISSUE THREAD

**Issue by bratpiorka** [memkind/memkind#481]
Let's assume that a node is HBW node when a bandwidth between it and initiator node is above some threshold, e.g. 204800 MiB/s. Also, assume we have a system with a topology where bandwidth values between the nodes are described by following table.

```
Node bandwidth [MiB/s]:
node     0      1      2      3      4      5      6 
  0:111000      X      X      X 204800      X      X 
  1:     X 111000      X      X      X 204800      X 
  2:     X      X 111000      X      X      X      X 
  3:     X      X      X 111000      X      X 204800 
  4:     -      -      -      -      -      -      - 
  5:     -      -      -      -      -      -      - 
  6:     -      -      -      -      -      -      - 
```

Then, when a CPU from node #2 wants to allocate memory using MEMKIND_HBW kind, this allocation should not succeed as there is no NUMA node that satisfies HBW conditions. Current implementation will try to allocate from node #0 which is wrong.

**Comment by michalbiesek** [comment]
Fixed by 839defa and 0ca11b5
