### ISSUE TITLE
question about longevity of hardwired memkind_t types

### ISSUE THREAD

**Issue by hppritcha** [memkind/memkind#49]
We have two issues filed against Open MPI concerning its usage of a now deprecated memkind api.
See 

open-mpi/ompi#4466  and open-mpi/ompi#4466

I've gone back through the memkind from past releases and noticed that the way to create a kind seems to vary, but the predefined ```memkind_t``` types (e.g.  MEMKIND_HBW_PREFERRED) seem to be relatively stable.   However, there's a comment around each of these defines about EXPERIMENTAL API that makes me a bit worried.  How stable are these pre-defined kinds and can one expect these to persist thru a  number of future memkind releases?

**Comment by hppritcha** [comment]
@Kkulakowski

**Comment by Kkulakowski** [comment]
Hi Howard,

thanks for reaching us out. I moved to another project in August and I no longer maintaining memkind. I'll make sure that someone from team taking care of memkind project will respond to you as soon as possible.

PS: would you mind to share info where did you found my name? Maybe there is some doc that needs to be updated with name of current maintainer.

Best Regards,
Krzysztof.

**Comment by hppritcha** [comment]
your github id is in the contributor list for this project.

**Comment by marcinkoss** [comment]
Hi Howard,
Thank you for your question.
Latest version of memkind from github should resolve your issue with compiling (see https://github.com/memkind/memkind/commit/8ab4ab01fc5a9acfa18446ab3fc5e1b61e91132b).
We currently do not have any plans in near future to remove or change static kinds.

Thanks
Marcin

**Comment by hppritcha** [comment]
thanks this is the information I needed.  closing.
