### ISSUE TITLE
RDMA buffer use case

### ISSUE THREAD

**Issue by chris1274** [memkind/memkind#522]
I would like to request a large region of memory from the operating system via mmap and register it for RDMA with ibv_reg_mr and then mount a memory allocator on top of that so that any buffer it returns will be RDMA accessible.

Can memkind support this kind of use case?

**Comment by michalbiesek** [comment]
Hi sorry for the late response.

Currently, memkind as heap manager provides support for PMEM in two forms:
- first one is MEMKIND_DAX_KMEM - as dev-dax namespace and system-ram mode
- second one - as file placed on the fs-dax namespace, where memory kind is created using memkind_create_pmem

Both forms are presented as memory kind abstraction - in other words, a separated memory heaps, where memkind is responsible not only for allocation into those heaps but also for creating/destroying them.

Regarding your issue, currently, memkind doesn't provide a handling heap ("request a large region of memory") passed from outside.

We would be happy to review a patch that would provide the described functionality.

**Comment by lukaszstolarczuk** [comment]
This issue has been untouched for a while. I'm allowing myself to close it. If you feel like this should be continued, please just re-open it or just file a new issue.
