### ISSUE TITLE
Can't instal memkind on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by meta1360** [memkind/memkind#54]
I downloaded "memkind-master" from https://github.com/memkind/memkind and I ran ./configure and make  where I hit to this error 
In file included from src/heap_manager.c:27:0:
./include/memkind/internal/memkind_arena.h:50:52: error: unknown type name 'extent_hooks_t'
 int memkind_arena_create_map(struct memkind *kind, extent_hooks_t *hooks);
It is worth mentioning that before that I also installed jemalloc-3.6.0/ before by running ./configure; make; make install.
I really appreciate if somebody tells me how to fix this.

**Comment by michalbiesek** [comment]
Hi,
Have You tried to follow instruction described in:
https://github.com/memkind/memkind/blob/629f1da866c6a7ade35e55bf825e827b66b90a96/CONTRIBUTING#L25
About jemalloc, please be aware of  memkind dependency:
https://github.com/memkind/memkind/blob/629f1da866c6a7ade35e55bf825e827b66b90a96/CONTRIBUTING#L59
