### ISSUE TITLE
Shared memory between processes using libmemkind

### ISSUE THREAD

**Issue by hesuyouren** [memkind/memkind#545]
Hi! 

I’m currently working on a project that requires sharing libmemkind memory across different processes, i.e., memory allocated via libmemkind by one process, can be read from or written to via libmemkind by another process. I’ve been exploring approaches that employ mmap over the same file from two different files to facilitate this, but I wasn’t sure about the internals on how libmemkind creates files and mmaps them.

Any help is greatly appreciated!

**Comment by michalbiesek** [comment]
Hi,

Sorry for a late answer - memkind doesn't provide an interface for handling files used underneath for the allocations. In fact, memkind doesn't read/write by itself; it uses a file for the purpose described in:
https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/man/memkind_pmem.3#L36-L39
The second application must be aware of where are exact data in the file, and the file could be punch holed: https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/src/memkind_pmem.c#L92 or even deleted: https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/src/memkind_pmem.c#L302
during work with the first application. 

Could you provide more information about the use case you want to use memkind?

**Comment by hesuyouren** [comment]
Thanks for your response @michalbiesek .

Here’s our use-case in a bit more detail: process A acts as a ‘manager’ for memory, handling allocation/deallocation requests via libmemkind, and process B uses (reads from/writes to) the same memory allocated by A. It essentially boils down to a special case of shared memory abstraction between processes A and B.

**Comment by lukaszstolarczuk** [comment]
It looks like this question is been answered for a while. I'm closing it. If you want to continue this discussion please re-open it or just file a new issue.
