### ISSUE TITLE
How to install memkind

### ISSUE THREAD

**Issue by meta1360** [memkind/memkind#55]
I have such a hard time to install memkind library. My goal is to be able to include 
#include <hbwmalloc.h>
in my cpp code. I read the READFILE and CONTRIBUTING but I could not understand if I need to install jemalloc-3.6.0 before installing mankind? 
I ran ./autogen ./configure  but when I run make I  get
make: *** No rule to make target `jemalloc/obj/lib/libjemalloc_pic.a', needed by `static_lib'.  Stop.
I have a folder named jemalloc but it does not have a subfolder called obj 
please help me out.

-thanks

**Comment by KFilipek** [comment]
Hi,
Running build_jemalloc.sh will build jemalloc inside memkind directory, you
can also try to run build.sh.



niedz., 8.07.2018, 19:09 użytkownik meta1360 <notifications@github.com>
napisał:

**Comment by marcinslusarz** [comment]
The well-established workflow for autoconf-based projects is this:

```
./autogen.sh && ./configure && make && make install
```

Requiring more steps makes such project less accessible. Please fix this.

**Comment by michalbiesek** [comment]
Fixed in #233
