### ISSUE TITLE
Concurrent calls to memkind_create_pmem with error code -13

### ISSUE THREAD

**Issue by githubxxcc** [memkind/memkind#56]
Hi, I am trying to build a multi-threading applications with memkind on persistent memory. 

Everything works fine when the number of threads islow.  However, when I increased the number of concurrent threads to 30, and one of the thread failed with MEMKIND_ERROR_INVALID (-13) when calling memkind_create_pmem. 
(Yes 29 is fine, is there a number of maximal mapping allowed?)
Does this have something to do with the value of `reserved` in `/include/memkind/tbb_mem_pool_policy.h` ?

Also, I am using Rust, thus calling the api from Rust' FFI, which I think should not be an issue here. 

I tried to set MEMKIND_DEBUG=1 to takea look at the traces and debug information. However, nothing was printed out. Wondering if simply setting MEMKIND_DEBUG=1 is enough to enable debugging? 

Thanks! 

(BTW, I am using release v1.7.0) 

**Updates**: 
I can only call memkind_create_pmem in your C example for 29 times, and the 30th invocation returns error. 
Any reason why such limit is imposed? And how can it be circumvented?

**Comment by michalbiesek** [comment]
Hi,
Sorry for the delayed response.

Could You provide me more information about:
**I can only call memkind_create_pmem in your C example for 29 times, and the 30th invocation returns error.**

I assume You used example/pmem_example.c and only changes You perform is to call memkind_create_pmem for 30 times and the 30th invocations returns error -13 ?

There is a limit in kind creation see MEMKIND_MAX_KIND which is equal 512 - which limits to create pmem kind to 498 - in this case function returns -15 ( MEMKIND_ERROR_TOOMANY ).

You could also hit the limit in function memkind_arena_create_map trying to call arenas.create too much times but in this case function returns -11.

For sure additional information ( maybe code examples ), regarding Your first problem and problem described in update section could help resolve this issue.

**Comment by KFilipek** [comment]
Hi, the only way to get error code -13 is passing third argument longer or equal to 64 to memkind_pmem_create() function.
I recommend to set conditional breakpoint under GDB to see what memkind_pmem_create() receive at the input or post code sample to reproduce the issue.
Best regards,
Krzysztof Filipek

**Comment by githubxxcc** [comment]
@michalbiesek 

Hi, thanks for your reply! Right, I did trace into the function `memkind_pmem_create`, and as you pointed out above, it is the 'memkind_arena_create_map' that is failing. `jemk_mallctl("arenas.create", ...)` fails when too many arenas have been created. 

**But the error code returns is '11' rather than '-11' when I tried to print it out.** 

Here is the modified source code of the main function in example/pmem_example.c: 
```
....
 /* create PMEM partition */
 102     int i= 0;
 103     while(++i){
 104         err = memkind_create_pmem(".", PMEM1_MAX_SIZE, &pmem_kind1);
 105         if (err) {
 106             perror("memkind_create_pmem()");
 107             fprintf(stderr, "Unable to create pmem partition %d\n", err);
 108             return errno ? -errno : 1;
 109         } else {
 110             fprintf(stdout, "Ok %d\n", i);
 111         }
 112     }

//stderr: 
//       " memkind_create_pmem() \n Unable to create pmem partition 11"
```


If I change MEMKIND_ARENA_NUM_PER_KIND to a smaller number, lets say 16, I can make 240 calls, and the maximal number of arenas seem to be 16*240 as well. And a smaller number will hit the maximal number of kind creation indeed. 

-------

However, with a smaller value of MEMKIND_ARENA_NUM_PER_KIND, it still doesn't quiet work in my multi-threading example. I am just spawning some threads, and each thread will call `memkind_pmem_create` once, 
1) it fails with a too small MEMKIND_ARENA_NUM_PER_KIND, returning err code -13
2) it fails with a too large MEMKIND_ARENA_NUM_PER_KIND, returning err code 11. 

The second case seems consistent with the example, not enough arenas. 

So that leaves me with 2 questions:
1. @KFilipek pointed out that the only case for an err code of -13 is "passing third argument longer or equal to 64 to memkind_pmem_create() function.", isn't the third argument the pointer to the kind? Not too sure if I get you correct. 
2.  Why the err code is 11 rather than -11? Am I missing out something obvious here regarding the sign?

**Comment by michalbiesek** [comment]
_Why the err code is 11 rather than -11? Am I missing out something obvious here regarding the sign?_
Yes, my mistake ( typo ) it was "11" not "-11"

**Comment by michalbiesek** [comment]
I have difficulties with recreate Your "multithread" scenario - if it is possible please share the code. 

_I am just spawning some threads, and each thread will call memkind_pmem_create once_

Just to ensure - Are You calling in Your example code directly function _memkind_pmem_create_ ?

I would check if there isn't a race condition. My suspicion is in function:
https://github.com/memkind/memkind/blob/629f1da866c6a7ade35e55bf825e827b66b90a96/src/memkind.c#L394

If let's say two threads want to create kind with the same "name" - one will finish with success but second will fail with error code -13 ( MEMKIND_ERROR_INVALID ):

To be precise, here:
https://github.com/memkind/memkind/blob/629f1da866c6a7ade35e55bf825e827b66b90a96/src/memkind.c#L420-L422

**Comment by githubxxcc** [comment]
I tried to recreate the multithread scenario in C : calling memkind_pmem_create at each thread. 

**Apparently that works.**  
So I believe it has something to do with my Rust program now, rather than you library. I will try to see where MEMKIND_ERROR_INVALID can be returned. 

You can close the issue. Really appreciate your time and help!
