### ISSUE TITLE
memkind_create_pmem() failed if other pmem kind was destroyed before 

### ISSUE THREAD

**Issue by vinser52** [memkind/memkind#57]
When we call **memkind_create_pmem()/memkind_destroy_kind()**  sequence several times only the first **memkind_create_pmem()** call completed successfully. All the following **memkind_create_pmem()** calls return error(-13 returned).

**Comment by vinser52** [comment]
We analyzed the issue and found the root cause.  The **memkind_destroy_kind()** call does not clean **memkind_registry_g.partition_map**

**Comment by michalbiesek** [comment]
Hi,
Sorry for the delayed response.
Thanks for reporting this issue, we will fix destroy method soon.
