### ISSUE TITLE
Capacity Lost Issue

### ISSUE THREAD

**Issue by winningsix** [memkind/memkind#58]
We're measuring the performance using Memkind library in Spark workload. But we find the capacity lost issue (the real used capacity at persistent memory side is larger than the data size we stored).  It’s possible some metadata or memory alignments occupies extra space. But it’s very critical to have a way understanding how much capacity it really allocated from persistent memory. For NVML or PMDK, we have the method like malloc_usable_size() but not supported in Memkind. It will make the upper application hard to make use of the full capacity of persistent memory. Given our workload as an example, our LRU based cache is based on Guava cache implementation. It encapsulates the logic of cache eviction that user only needs to pass in the size of each allocation. In lack of direct way to obtain the real capacity of persistent memory allocation, we have to leave out some “safe volumes” to ensure the new allocation can be done successfully but it's real not user-friendly.

**Comment by michalbiesek** [comment]
memkind_malloc_usable_size is now provide for memkind API.

**Comment by lukaszstolarczuk** [comment]
I hope the API extension delivered by Michał is sufficient to mark this issue as resolved. Since there were no updates here, I'm allowing myself to close it.
