### ISSUE TITLE
Persistence of PMEMALLOCATOR

### ISSUE THREAD

**Issue by YFatish** [memkind/memkind#616]
Hello!

I am a newbie in persistent programming and I am learning how to use memkind. 
There is one thing I am confused about.  Will the data allocated using PMEMALLOCATOR be persistent? Or that PMEMALLOCATOR uses PM as an expansion of DRAM?

Any help is greatly appreciated!

**Comment by michalbiesek** [comment]
Hi,
[Pmemallocator](https://github.com/memkind/memkind/blob/master/man/pmemallocator.3) uses PMem as an expansion of DRAM.

**Comment by YFatish** [comment]
Thank you very much!  : )
