### ISSUE TITLE
set MEMKIND_DAX_KMEM_PREFERRED

### ISSUE THREAD

**Issue by mkatsa** [memkind/memkind#672]
Hello,

As far as I can understand MEMKIND_DAX_KMEM_PREFERRED is an environment variable that needs to be set prior to the application's execution.
Will export $MEMKIND_DAX_KMEM_PREFERRED=1 work? Or does it require something else?

Thanks

**Comment by michalbiesek** [comment]
Hi @mkatsa,

Thank you for your message. **MEMKIND_DAX_KMEM_PREFERRED** is an example representation of the memory kinds available in the memkind library. Memory kind is a type of abstraction for different types of memory.
**MEMKIND_DAX_KMEM_PREFERRED** is one of the static kind already defined in the memkind interface described in http://memkind.github.io/memkind/man_pages/memkind.html#KINDS
**MEMKIND_DAX_KMEM_PREFERRED* it is not an environment variable. It is a representation of type _memkind_t_ - see http://memkind.github.io/memkind/man_pages/memkind.html#DESCRIPTION heap management API for details.

This post shows the actual behavior of MEMKIND_DAX_KMEM_PREFERRED and the difference between MEMKIND_DAX_KMEM_ALL/MEMKIND_DAX_KMEM:
https://pmem.io/2020/01/20/memkind-dax-kmem.html

Please let me know if you have any more questions.

Best Regards Michal

**Comment by mkatsa** [comment]
Thank you! I was confused on this.
