### ISSUE TITLE
memkind_create_pmem() several calls failed with error code 11

### ISSUE THREAD

**Issue by Epromee** [memkind/memkind#72]
When several pmem kinds are being created one by one, on 15'th call ` memkind_create_pmem ` gets failed with error code 11, so that we are able to create 14 pmem kinds only (this number however may be system-dependent).

It was found while debugging, that this error is returned from `jemk_mallctl` call from function `memkind_arena_create_map`, which is defined in `memkind_arena.c` file.

```cpp
#include <iostream>
#include "memkind.h"

int main() {
    const char* dir = "/dev/shm";
    const size_t size = 1024 * 1024 * 1024;
    const size_t iters = 20;

    memkind_t kind[iters]; 
    
    std::cout << "Trying to create " << iters << " pmem kinds" << std::endl;

    size_t i;

    for (i = 0; i < iters; ++i) {
         auto err = memkind_create_pmem(dir, size, &(kind[i]));
         if (err) {
            std::cout << "Failure on kind creation number: " << (i + 1) << std::endl;
            break;
         } else {
            std::cout << "Success on kind creation number: " << (i + 1) << std::endl;
         }
    }

    std::cout << "Memkinds created successfully: " << i <<  "/" << iters << std::endl; 
    
    while (i > 0) {   
        --i;
        memkind_destroy_kind(kind[i]);
    }
    
    return 0;
}

```

**Comment by michalbiesek** [comment]
You hit the limit in function memkind_arena_create_map trying to call jemk_mallctl("arenas.create") too much times - in fact the operation is really failing on jemalloc side.

 _(this number however may be system-dependent)_
It is, please see memkind_set_arena_map_len and calculation of calculated_arena_num.
You could try to change this value using ARENA_LIMIT_PER_KIND.

About error code 11:
Recently error code MEMKIND_ERROR_ARENAS_CREATE was added to inform about fail in case of memkind_create_pmem operation it will provide clear information for user what happened ( error code 11 was confusing)
