### ISSUE TITLE
PMEM kind ignores MEMKIND_HEAP_MANAGER environment

### ISSUE THREAD

**Issue by vinser52** [memkind/memkind#73]
We found that PMEM kind always use jemalloc as a memory manager. Even we setup environment MEMKIND_HEAP_MANAGER=TBB it is ignored. 

We found that `memkind_pmem_create()` calls `memkind_default_create()` which does not call `heap_manager_init` and just uses jemalloc routines.

**Comment by michalbiesek** [comment]
TBB isn't currently supported by PMEM kind - only jemalloc is.

**Comment by vinser52** [comment]
Can we consider it as a feature request?

**Comment by lukaszstolarczuk** [comment]
Feature request is included in the list here: https://github.com/memkind/memkind/issues/185

Closing this.
