### ISSUE TITLE
a64fx support?

### ISSUE THREAD

**Issue by tonycurtis** [memkind/memkind#765]
Hi, was playing with memkind on an a64fx cluster.  Is there any support for its HBM?

**Comment by bratpiorka** [comment]
Yes, Memkind supports allocation on HBM (but we called it HBW - high-bandwidth memory). Please look at MEMKIND_HBW* kinds in the readme and at examples/hello_hbw_example.c. You could also play with "autohbw" lib that allocates data on HBW memory without any modification to the program - see autohbw/autohbw_README.

**Comment by tonycurtis** [comment]
Thanks, will take a look

**Comment by tonycurtis** [comment]
Had a poke.  The a64fx has **only** HBM so calls like hbw_malloc fail.  Is that expected (e.g. because there is no other memory to differentiate)?

**Comment by bratpiorka** [comment]
Could you write what is the output from "numactl -H"? If there are problems with auto-detection you could always set MEMKIND_HBW_NODES environmental variable. There is a paragraph in Readme that describes it, but please simply set to NUMA node ID with HBM memory. If there is no other memory in your system, you should probably set it to 0.

**Comment by tonycurtis** [comment]
Ah, MEMKIND_HBW_NODES helps a lot!  Seeing sensible output.  Thanks!

```
$ numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1 2 3 4 5 6 7 8 9 10 11
node 0 size: 8096 MB
node 0 free: 5490 MB
node 1 cpus: 12 13 14 15 16 17 18 19 20 21 22 23
node 1 size: 8181 MB
node 1 free: 6277 MB
node 2 cpus: 24 25 26 27 28 29 30 31 32 33 34 35
node 2 size: 8181 MB
node 2 free: 6773 MB
node 3 cpus: 36 37 38 39 40 41 42 43 44 45 46 47
node 3 size: 8161 MB
node 3 free: 6654 MB
node distances:
node   0   1   2   3
  0:  10  20  30  30
  1:  20  10  30  30
  2:  30  30  10  20
  3:  30  30  20  10
```

**Comment by tonycurtis** [comment]
```
$ memkind-hbw-nodes
$ export MEMKIND_HBW_NODES=0-3
$ memkind-hbw-nodes
0,1,2,3
```
