### ISSUE TITLE
how to decrease allocation overhead 

### ISSUE THREAD

**Issue by chenyou-intel** [memkind/memkind#825]
We have an use case that each allocation is around 2KB on PMem using FSDAX mode. However, I found each allocation will bring in ~360 bytes extra PMem space using below code snippet:

```cpp
memkind *pmem = nullptr;  
size_t max_size = 5LL * 1024 * 1024 * 1024;
int ret = memkind_create_pmem("/mnt/pmem0/p_cache", max_size, &pmem);
size_t raw = 2196;
for (int i = 0; i < 3000000; i++) {
    char *ptr = (char *) memkind_malloc(pmem, raw);
    if (ptr) {
        cout << memkind_malloc_usable_size(pmem, (void *) ptr) - raw << endl;
    }
    if (ptr == nullptr) {
        break;
    }
}
```

Therefore, we could only use ~85% of the PMem capacity. It's there any way to decrease this extra space needed?
Thanks!

**Comment by bratpiorka** [comment]
Memkind is based on the jemalloc allocator... Could you check if this snippet works when you use jemalloc directly? Jemalloc is already included in the memkind source code. Just include jemalloc.h and just call malloc()/malloc_usable_size() directly from this library - how much memory overhead will you see then?

**Comment by chenyou-intel** [comment]
@bratpiorka 
Hi, I've changed the code to:

```cpp
 
    #include <jemalloc/jemalloc.h>
    /*
    memkind *pmem = nullptr;
    size_t max_size = 5LL * 1024 * 1024 * 1024;
    int ret = memkind_create_pmem("/mnt/pmem0/p_cache", max_size, &pmem);
     */
    size_t raw = 2196;
    for (int i = 0; i < 3000000; i++) {
        //char *ptr = (char *) memkind_malloc(pmem, raw);
        char *ptr = (char *) malloc(raw);
        if (ptr) {
            //cout << memkind_malloc_usable_size(pmem, (void *) ptr) - raw << endl;
            cout << malloc_usable_size((void *) ptr) - raw << endl;
        }
        if (ptr == nullptr) {
            break;
        }
    }
```

And only see 4 bytes overhead with simple malloc / malloc_usable_size.

**Comment by bratpiorka** [comment]
@chenyou-intel 
Are you sure you linked jemalloc correctly? With "-L/usr/local/lib -ljemalloc" linker options I got 364 bytes overhead. Please look at https://github.com/jemalloc/jemalloc/wiki/Getting-Started for details on how to link statically to jemalloc lib.

Looking at jemalloc documentation, all allocations made by it are grouped into pools that differ in size. The allocation size used in your example (2196 bytes) fits into the "small" 2560 class (see https://jemalloc.net/jemalloc.3.html table 1 "Size classes"). 2560 - 2196 = 364 so this is correct. 

All fast, pool-based allocators uses similar "size classes" mechanism, there is no way to avoid this.

**Comment by chenyou-intel** [comment]
@bratpiorka Sorry for the mistake, I omit this link flag. I also got 364 bytes overhead after added it. Thanks for the help.
