### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by anghostcici** [memkind/memkind#9]
Hi,
When I followed the step as below, 
git clone https://github.com/memkind/memkind.git
    cd memkind
    ./autogen.sh
    cd jemalloc
    autoconf
    mkdir obj
    cd obj
    ../configure --enable-autogen --with-jemalloc-prefix=jemk_ \
                 --enable-memkind --enable-cc-silence
    make
    cd ../..
    ./configure --prefix=$HOME/build
    make
    make install
    find $HOME/build # This command just lists out what was installed

I had an error when I compiled the memkind : 

libtool: link: `jemalloc/obj/src/jemalloc.lo' is not a valid libtool object
Makefile:1333: recipe for target 'libmemkind.la' failed
make[1]: *** [libmemkind.la] Error 1
make[1]: Leaving directory '/home/chnie/memkind'
Makefile:1188: recipe for target 'all' failed
make: *** [all] Error 2

I don't figure out how to solve this error. Could you please give some suggestions about the possible reason for the error? 

Thanks a bunch!

**Comment by cmcantalupo** [comment]
@anghostcici

I'm guessing it is related to this patch:

152f5cbe1a32441ec26a94736f00b5648bb9618a

Can you try reverting this commit and seeing if it fixes your issue?

Can you also show me the output of

   libtool --version

on you system?

Thanks!

**Comment by anghostcici** [comment]
It doesn't work, I still have the same issue.
My libtool version is : libtool (GNU libtool) 2.4.2

**Comment by anghostcici** [comment]
Yes, it works now to use the reverted Makefile.am. Thanks!
My libtool version is : libtool (GNU libtool) 2.4.2.

**Comment by thedrow** [comment]
I can confirm the same issue on Ubuntu 15.10.
My libtool version is also 2.4.2.

**Comment by thedrow** [comment]
It seems that the latest version is [2.4.6](http://git.savannah.gnu.org/cgit/libtool.git/tag/?id=v2.4.6).
Is there a bug fixed in that version?

**Comment by thedrow** [comment]
Reverting the commit fixes it for me as well.

**Comment by cmcantalupo** [comment]
I'm afraid the "better solution" for integrating jemalloc with memkind use of libtool is not, in fact, better.  Probably the best solution is just to revert the commit and continue linking against the static jemalloc library rather than the jemalloc object files.  

This problem may be specific to Ubuntu.  I'm using libtool 2.4.2 on CentOS 7.1 with no issue.  

Thanks for the feedback.
